version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "666:80/tcp"
    networks:
      - proxy
    environment:
      TZ: 'Europe/Prague'
    volumes:
      - '/mnt/vault/containers/pihole/etc-pihole:/etc/pihole'
      - '/mnt/vault/containers/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped

networks:
  proxy:
    external: true
