version: "3"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer_dashboard
    ports:
      - "5656:8080"
    networks:
      - proxy
    environment:
      INIT_ASSETS: 1
    volumes:
      - /mnt/vault/containers/homer/:/www/assets
    restart: unless-stopped

networks:
  proxy:
    external: true 
