version: "2.1"
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    volumes:
      - /mnt/vault/containers/librespeed/config:/config
    ports:
      - 39878:80
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
