version: "3.5"
services:
  glances:
    container_name: glances
    image: joweisberg/glances:latest
    restart: unless-stopped
    pid: host
    ports:
      - 61208:61208
    networks:
      - proxy
    environment:
      - TZ=Europe/Prague
      - GLANCES_OPT=--webserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/vault/containers/glances/config:/glances/conf

networks:
  proxy:
    external: true
