version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
    networks:
      - proxy
    volumes:
      - /mnt/vault/containers/jellyfin/config:/config
      - /mnt/vault/containers/jellyfin/media/TVshows:/data/tvshows
      - /mnt/vault/containers/jellyfin/media/Movies:/data/movies
    ports:
      - 8096:8096
      #- 8920:8920 #HTTPS
    devices:
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/video12:/dev/video12"
    restart: unless-stopped

networks:
  proxy:
    external: true
