version: "3"
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.9.3
    security_opt:
      - no-new-privileges:true
    ports:
      - "8000:8000"
      - "9443:9443"
      - "9000:9000"
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/vault/containers/portainer:/data
    restart: unless-stopped
    #labels:
      #- "traefik.enable=true"
      #- "traefik.http.routers.portainer.entrypoints=http"
      #- "traefik.http.routers.portainer.rule=Host(`portainer.local.bmarlab.com`)"
      #- "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      #- "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      #- "traefik.http.routers.portainer-secure.entrypoints=https"
      #- "traefik.http.routers.portainer-secure.rule=Host(`portainer.local.bmarlab.com`)"
      #- "traefik.http.routers.portainer-secure.tls=true"
      #- "traefik.http.routers.portainer-secure.service=portainer"
      #- "traefik.http.services.portainer.loadbalancer.server.port=9000"
      #- "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
