version: '2'
services:
  web:
    ports:
      - 8796:8000
    networks:
      - proxy
    volumes:
      - ~:/root
      - /:/mnt/fs
    image: coderaiser/cloudcmd
    restart: unless-stopped

networks:
  proxy:
    external: true
