version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "7777:8081"
    networks:
      - proxy
    volumes:
      - /mnt/vault/containers/qbittorrent/downloads:/downloads

networks:
  proxy:
    external: true
